export {default as Biography} from './biography'
export {default as Work} from './work'
export {default as Contact} from './contact'
export {default as Education} from './education'
export {default as Interests} from './interests'
export {default as Skills} from './skills'
