export {default as Navbar} from './navbar'
export {default as Projects} from './projects'
export {default as Introduction} from './introduction'
export {default as Skills} from './skills'
export {default as Contact} from './contact'
export {default as About} from './about'
